#pragma once



#define CLIENT_TEXT					"Client"
#define CLIENT_REQUEST_VALUE_TEXT	"CLIENT_REQUEST_VALUE"
#define CLIENT_REQUEST_LEADER_TEXT	"CLIENT_REQUEST_LEADER"
#define CLIENT_PING_TEXT			"CLIENT_PING"




#define SEMAPHORE_RECEIVE_LEADER	1
#define SEMAPHORE_COMMIT_VALUE		1
#define TIME_WAITING_A_LEADER		10000//(ms)
#define TIME_WAITING_COMMIT_VALUE	30000//(ms)

